import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Timmana } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const timmana = Timmana({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-timmana",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${timmana.variable}`}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inria+Sans&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-inter">{children}</body>
    </html>
  );
}
